#　服务配置：设置gin的运行模式，默认的http监听端口，允许读取和写入的最大持续时间
Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

#  应用配置：设置默认每页数量，所允许的最大每页数量，以及默认的应用日志存储地址
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/log
  LogFileName: app
  LogFileExt: .log

  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 15 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png


#  数据库配置：主要是链接实例所需的基础参数
Database:
  DBType: mysql
  Username: root
  Password: ******
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

# JWT权限设计
JWT:
  Secret: wenhao
  Issuer: blog_service
  Expire: 7200

Email:
  Host: smtp.qq.com
  Port: 465
  UserName: ****@qq.com
  Password: ******
  IsSSL: true
  From: *****@qq.com
  To:
    - *****@qq.com